### ISSUE TITLE
使用后无法删除

### ISSUE THREAD

**Issue by oct16** [gengchen528/douEdit#1]

**Comment by gengchen528** [comment]
> _No description provided._

请问你是指删除评论无法删除还是自己发布的帖子呢

**Comment by oct16** [comment]
只试了一下评论

**Comment by gengchen528** [comment]
> 只试了一下评论

如果是自己帖子的评论的话应该是没问题的，但如果是删除在其他人帖子的留言可能会出问题，因为有分页的原因
